spring:
  application:
    name: finalExam
  datasource:
    url: jdbc:postgresql://localhost:5400/USERS-DB
    username: postgres
    password: users123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8099